### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by rbracewell** [kronicle-tech/kronicle-docker-compose#10]
When running docker-compose up I run into the following issue.

Attaching to kronicle-docker-compose-kronicle-app-1, kronicle-docker-compose-kronicle-service-1
kronicle-docker-compose-kronicle-app-1      | ℹ [HPM] Proxy created: /api  -> http://kronicle-service:8090
kronicle-docker-compose-kronicle-app-1      | ℹ [HPM] Proxy rewrite rule created: "^/api($|/)" ~> "/"
kronicle-docker-compose-kronicle-app-1      | ℹ Listening on: http://172.18.0.3:3000/
kronicle-docker-compose-kronicle-app-1      | {"appName":"kronicle-app","appVersion":"0.1.167","headers":{"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-encoding":"gzip, deflate","accept-language":"en-GB,en;q=0.9","connection":"keep-alive","host":"localhost:3000","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15"},"level":"error","message":{},"method":"GET","url":"/"}
kronicle-docker-compose-kronicle-app-1      |
kronicle-docker-compose-kronicle-app-1      |  ERROR  request to http://kronicle-service:8090/v1/areas?fields=areas(id) failed, reason: connect ECONNREFUSED 172.18.0.2:8090
kronicle-docker-compose-kronicle-app-1      |
kronicle-docker-compose-kronicle-app-1      |   at ClientRequest.<anonymous> (node_modules/node-fetch/lib/index.js:1491:11)
kronicle-docker-compose-kronicle-app-1      |   at ClientRequest.emit (node:events:526:28)
kronicle-docker-compose-kronicle-app-1      |   at Socket.socketErrorListener (node:_http_client:442:9)
kronicle-docker-compose-kronicle-app-1      |   at Socket.emit (node:events:526:28)
kronicle-docker-compose-kronicle-app-1      |   at emitErrorNT (node:internal/streams/destroy:157:8)
kronicle-docker-compose-kronicle-app-1      |   at emitErrorCloseNT (node:internal/streams/destroy:122:3)
kronicle-docker-compose-kronicle-app-1      |   at processTicksAndRejections (node:internal/process/task_queues:83:21)
kronicle-docker-compose-kronicle-app-1      |
kronicle-docker-compose-kronicle-app-1      |
kronicle-docker-compose-kronicle-app-1      |  ERROR  request to http://kronicle-service:8090/v1/areas?fields=areas(id) failed, reason: connect ECONNREFUSED 172.18.0.2:8090
kronicle-docker-compose-kronicle-app-1      |
kronicle-docker-compose-kronicle-app-1      |   at ClientRequest.<anonymous> (node_modules/node-fetch/lib/index.js:1491:11)
kronicle-docker-compose-kronicle-app-1      |   at ClientRequest.emit (node:events:526:28)
kronicle-docker-compose-kronicle-app-1      |   at Socket.socketErrorListener (node:_http_client:442:9)
kronicle-docker-compose-kronicle-app-1      |   at Socket.emit (node:events:526:28)
kronicle-docker-compose-kronicle-app-1      |   at emitErrorNT (node:internal/streams/destroy:157:8)
kronicle-docker-compose-kronicle-app-1      |   at emitErrorCloseNT (node:internal/streams/destroy:122:3)
kronicle-docker-compose-kronicle-app-1      |   at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by simondean** [comment]
Hi @rbracewell.  It might be due to the start up time for the backend service.  Do you get logs for `kronicle-service` after about 20-30 seconds?  It'll show as `kronicle-docker-compose-kronicle-service-1`

**Comment by simondean** [comment]
There's  node.js based web app (`kronicle-app`) and a Spring Boot based backend service (`kronicle-service`).

**Comment by rbracewell** [comment]
Ah yes if I wait a while and refresh the browser the page loads. I do also get the logs showing as well after several seconds.
I will close with this comment.

**Comment by simondean** [comment]
Thanks, I'll update the documentation with a note on it
